funding proposal function frontend
deora-earth/rosebudDAO pull request #22
Opened 2020-01-29 11:05 UTC by simonweniger

- first changes form proposal submission to funding submission
- minor changed to members view

2020-01-31 14:00 UTC, MaxStalker requested changes

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/App.js
> +                path="/fundingsubmission"
```suggestion
                path="/funding-submission"
```

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/MemberList.js
>      <Link to={`/members/${address}`} className="uncolored">
Move whole Link block on "tab" stop to the right :)
Also you can run prettier on this file (and all the rest that you've touched). This shall reformat code to make it more consistent and "correct"

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/ProposalList.js
> +                      <Link to="/proposalsubmission" className="uncolored">
```suggestion
                      <Link to="/proposal-submission" className="uncolored">
```

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/ProposalList.js
> +                      <Link to="/fundingsubmission" className="uncolored">
```suggestion
                      <Link to="/funding-submission" className="uncolored">
```

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/index.scss
> +  #newPorposalDropdown{
Don't style the elements by identificator. This might shoot you in the leg :)
Also in CSS it's more common to use "kebab-case", i.e. words separated with dashes.

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +        console.log("value: ", value);
Usually, you remove all the console logging - except for some crucial stuff - when you submit a PR ;)

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +    );
You can refactor this one a bit to make it a bit DRY:
```
  let isValid = null;
  switch (fieldName){
    case "address":
      isValid = utils.isHexString(value);
      break;
    case "amount":
      isValid = value > 0;
      break;
    default:
      isValid = value && value !== "";
      break;
  }
  const capitalizedFieldName = fieldName.replace(/^\w/, c => c.toUpperCase());
  fieldValidationErrors[fieldName] = isValid ? "" : `${capitalizedFieldName} is invalid`;

  const fieldKey = `${fieldName}Valid`;
  this.setState({
    fieldValidationErrors,
    [fieldKey]: isValid
  });
```

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +    console.log("Shares " + shares)
Here is safe to remove logging.

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +    console.log(shareValue);
Safe to delete ;)

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +      );
Remove as well.

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +    });
It's better to move this inside ```try``` block

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +            if (loading) return <p>Loading...</p>//<Loader size="massive" active />;
Remove inline comment or replace with that loader. You can add `return` before it and then all the code below won't be processed.

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +            console.log({shareValue});
Safe to remove

2020-01-31 14:00 UTC, MaxStalker commented on packages/frontend/src/components/FundingSubmission.js
> +                {/* <Button size="large" color="red" onClick={this.handleSubmit}>
You can delete it if you don't need it ;)

2020-01-31 17:00 UTC, simonweniger commented on packages/frontend/src/index.scss
> +  #newPorposalDropdown{
where should i style them ? @MaxStalker  right at the UI element ?

2020-01-31 17:01 UTC, simonweniger commented
did some of the requested changes and also installed and run prettier on every document i touched. Pleas have a look @MaxStalker

2020-02-01 20:30 UTC, MaxStalker reviewed
Other than included node_modules - all cool :)

2020-02-02 16:57 UTC, MaxStalker approved these changes
Well done 👍

2020-02-03 16:57 UTC, merged